### ISSUE TITLE
Compile error when cross-compiling for Windows using MinGW-W64

### ISSUE THREAD

**Issue by rubenwardy** [emilk/loguru#128]
Hey, thanks for making this library! I thought I'd update it today, but I now have this compile error when compiling for Windows:

```
loguru.cpp:(.text+0x2e97): undefined reference to `__imp__dupenv_s'
```

The Windows build environment can be reproduced here: https://gitlab.com/rubenwardy/docker-sfml-rvwp/blob/master/install_mingw.sh

**Comment by rubenwardy** [comment]
https://github.com/emilk/loguru/blame/master/loguru.cpp#L662-L665

This issue appears to be introduced by https://github.com/emilk/loguru/commit/86b8c648ff7cf2c49ed4c6c64e413fa61a420225

**Comment by emilk** [comment]
Windows compilations proves to be an ongoing issue for Loguru. Microsoft has in their infinitesimal wisdom decided to take standard function names and deprecate them and/or rename them, and do so differently for different version of their compiler. We seem to be stuck in a loop of "here is a PR that fixes Windows compilation for me, but breaks it for someone else". We either need a better CI with many versions of MSVC, or a dedicated champion for getting Loguru to work well on Windows.

Since I I don't even have a Windows installation I will just watch on from the sidelines and merge PRs that people send in. So long as they don't break the Mac/*nix builds, I'm good :)

**Comment by rubenwardy** [comment]
I also don't have Windows, my technique for supporting it is a mixture of CI and praying

I've fixed my CI build by reverting the commit I linked, the old getenv version compiles fine. When I need to test the Windows version or give it to people then I'll have to fix the issue properly. This is a personal project so may never happen :)

**Comment by Lazzu** [comment]
I'm getting this fixed on MinGW when I replace line 661 with `#ifdef _MSC_VER` so it only detects if it's compiling it on MSVC.

**Comment by ambarishsatheesh** [comment]
> I'm getting this fixed on MinGW-W64 when I replace line 661 with `#ifdef _MSC_VER` so it only detects if it's compiling it on MSVC.

Thanks, this also fixed the issue for me too

**Comment by pulsefire** [comment]
> 
> 
> I'm getting this fixed on MinGW-W64 when I replace line 661 with `#ifdef _MSC_VER` so it only detects if it's compiling it on MSVC.

Thanks, this solved it for me.
