### PR TITLE
Consolidating external dependencies

### PR DESCRIPTION
**Pull request by tusharpm**
This PR contains
- the changes to collect Glog dependent projects (glog_bench and glog_example) under one directory.
- the build script `build_and_run.cmake` (instead of shell), to use on Windows also.
- A README.md explaining the key advantages of this approach, the build steps and a sample output (taken from Windows).

This allows running the glog_* tests on all platforms (with CMake). The same can be followed further for the internal tests (loguru_bench and loguru_example).

### CODE REVIEW

**Comment by emilk** [comment]
Impressive improvements! However, this PR causes problems on my Mac:

```
loguru/external > cmake -P build_and_run.cmake

...

/Users/emilk/kod/loguru/external/glog/src/utilities.cc:141:7: error: use of undeclared identifier 'IsFailureSignalHandlerInstalled'
  if (IsFailureSignalHandlerInstalled()) {
      ^
/Users/emilk/kod/loguru/external/glog/src/utilities.cc:254:17: warning: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Wdeprecated-declarations]
    pid_t tid = syscall(__NR_gettid);
                ^
/usr/include/unistd.h:733:6: note: 'syscall' has been explicitly marked deprecated here
int      syscall(int, ...);
```

The glog benchamrks/examples on the `master` branch both works (in those cases I am uses pre-compiled glog 0.3.4 from macports). Any ideas what is going wrong here? Maybe the submodule should be the `0.3.4` tag?

**Comment by tusharpm** [comment]
[Copy pasting from my reply to the email - GitHub notifications didn't pick that one up]

Thanks for writing back. I’ll try to address your concern to the best of my ability.

The primary problem I faced with glog v0.3.4 was that it didn’t have a CMakeLists.txt file. It’s not surprising considering the release is almost two years old (will be this March). This makes it difficult to be able to build it with the same commands across platforms (Linux, macOS and Windows). I chose the latest master because it has CMake support to build on all platforms (I tried Linux and Windows; evidently missed macOS).

The error you describe is in glog code. I’ll check if it builds independently on my mac.

(Just ran the tests): It builds fine (with the warnings though) on my machine (Sierra 10.12.2). To help you further, I need more details from your build environment – for instance the compiler you use (Apple clang? Version?) and any external factors that may have affected the build, like the GFlags namespace option, etc.

**Comment by emilk** [comment]
Has this PR been superseded by the merging of https://github.com/emilk/loguru/pull/28? Can I close this?

**Comment by tusharpm** [comment]
[happened again with GitHub notification]
No. These PRs are mutually exclusive. This one modifies the build procedure of the glog-dependant projects in loguru to enable them on all platforms. #28 builds and tests loguru (with CI integration).

I believe we can address the concerns you had brought up earlier and merge this one separately. Meanwhile, I can try to keep this fast-forwardable.

**Comment by emilk** [comment]
Closing this as it has gone stale, but thanks for the PR!
